include:
  - compose-db.yml

services:
  e-commerce:
    image: e-commerce/ggruzdov-demo-app:1.0
    container_name: e-commerce
    ports:
      - '8080:8080'
    environment:
      - 'POSTGRES_HOST=ecommerce-db'
    depends_on:
      - postgres
    restart: always