services:
  postgres:
    container_name: ecommerce-db
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'