CREATE TABLE categories(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100) NOT NULL,
    parent_id   INTEGER,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE attribute_definitions(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id      INTEGER NOT NULL,
    name             VARCHAR(100) NOT NULL,
    type             VARCHAR(30) NOT NULL,
    values           JSONB,
    is_optional      BOOLEAN NOT NULL,
    display_order    INTEGER NOT NULL,
    CONSTRAINT pk_attribute_definitions PRIMARY KEY (id),
    CONSTRAINT fk_attribute_definitions_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE products(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku         VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    category_id INTEGER      NOT NULL,
    brand       VARCHAR(50)  NOT NULL DEFAULT 'Other',
    price       INTEGER      NOT NULL,
    weight      DECIMAL      NOT NULL,
    description TEXT         NOT NULL,
    attributes  JSONB        NOT NULL,
    created_at  TIMESTAMP DEFAULT clock_timestamp(),
    updated_at  TIMESTAMP,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE INDEX idx_product_category_price ON products (category_id, price);
CREATE INDEX idx_product_brand ON products (brand);

CREATE INDEX idx_product_description_text_search
ON products
USING gin (to_tsvector('english', description));