CREATE TABLE categories(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100) NOT NULL,
    parent_id   INTEGER,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE attribute_definitions(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id      INTEGER NOT NULL,
    name             VARCHAR(100) NOT NULL,
    type             VARCHAR(30) NOT NULL,
    is_required      BOOLEAN NOT NULL,
    validation_rules TEXT,
    display_order    INTEGER NOT NULL,
    CONSTRAINT pk_attribute_definitions PRIMARY KEY (id),
    CONSTRAINT fk_attribute_definitions_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE products(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku         VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    category_id INTEGER      NOT NULL,
    description VARCHAR(255) NOT NULL,
    price       INTEGER      NOT NULL,
    weight      DECIMAL      NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE product_attributes(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       INTEGER NOT NULL,
    attribute_def_id INTEGER NOT NULL,
    value            TEXT    NOT NULL,
    CONSTRAINT pk_product_attributes PRIMARY KEY (id),
    CONSTRAINT fk_product_attributes_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_product_attributes_attr_def FOREIGN KEY (attribute_def_id) REFERENCES attribute_definitions (id)
);